"""Generate Obd2DtcDb.h from a CSV of OBD-II DTC descriptions.

Input CSV format:
    category,code,description
    P,0420,Catalyst System Efficiency Below Threshold (Bank 1)
    U,0100,Lost Communication with ECM/PCM
    ...

- `category` is one of P, C, B, U (one ASCII character)
- `code` is a 4-character uppercase hex string (no 0x prefix)
- `description` is the human-readable phrase; may contain commas only
  if quoted per RFC 4180 (the csv module handles that)

Output: a self-contained C++17 header at the path given by --out. The
header declares a `constexpr std::array<tDtcDbEntry, N>` named
`c_dtcDb` in namespace `subiediag::obd2`, sorted by (category, code)
ascending, with N inferred from the input.

CLI: gen_obd2_dtcs.py path/to/dtcs.csv --out path/to/Obd2DtcDb.h
"""

from __future__ import annotations

import argparse
import csv
import datetime
import hashlib
import sys
from pathlib import Path


_CATEGORY_MAP = {
    "P": "eDtcCategory::Powertrain",
    "C": "eDtcCategory::Chassis",
    "B": "eDtcCategory::Body",
    "U": "eDtcCategory::Network",
}


def _cpp_string(s: str) -> str:
    """Escape a Python string as a C++ string literal."""
    if not s:
        return '""'
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 32 <= cp <= 126:
            out.append(ch)
        else:
            out.append(f"\\x{cp:02x}")
    return '"' + "".join(out) + '"'


def _parse_csv(path: Path) -> list[tuple[str, int, str]]:
    """Returns list of (category, code_int, description), sorted."""
    rows: list[tuple[str, int, str]] = []
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for lineno, row in enumerate(reader, start=2):
            cat = (row.get("category") or "").strip().upper()
            code_str = (row.get("code") or "").strip()
            desc = (row.get("description") or "").strip()
            if not cat or not code_str:
                continue
            if cat not in _CATEGORY_MAP:
                raise ValueError(f"{path}:{lineno}: unknown category {cat!r}")
            try:
                code_int = int(code_str, 16)
            except ValueError as e:
                raise ValueError(f"{path}:{lineno}: bad code {code_str!r}: {e}") from None
            if not (0 <= code_int <= 0x3FFF):
                raise ValueError(f"{path}:{lineno}: code {code_str!r} outside 14-bit range")
            rows.append((cat, code_int, desc))
    # Sort by category (P, C, B, U order via enum), then by code.
    cat_order = {"P": 0, "C": 1, "B": 2, "U": 3}
    rows.sort(key=lambda r: (cat_order[r[0]], r[1]))
    return rows


def _emit(rows: list[tuple[str, int, str]], src_path: Path, out_path: Path) -> None:
    src_hash = hashlib.sha256(src_path.read_bytes()).hexdigest()[:16]
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    lines: list[str] = []
    w = lines.append

    w(f"// {out_path.name} - auto-generated by gen_obd2_dtcs.py")
    w("// DO NOT EDIT - regenerate from obd2_generic_dtcs.csv")
    w("//")
    w(f"// Source CSV : {src_path.name}  (sha256:{src_hash}...)")
    w(f"// Entries    : {len(rows)}")
    w(f"// Generated  : {timestamp}")
    w("")
    w("#pragma once")
    w("")
    w('#include "subiediag/Obd2.h"')
    w("")
    w("#include <stddef.h>")
    w("#include <stdint.h>")
    w("")
    w("#include <array>")
    w("#include <string_view>")
    w("")
    w("namespace subiediag::obd2")
    w("{")
    w("")
    w("    struct tDtcDbEntry")
    w("    {")
    w("        eDtcCategory     category;")
    w("        uint16_t         code;")
    w("        std::string_view description;")
    w("    };")
    w("")
    w(f"    // Sorted by (category, code). Lookup is a linear scan -- {len(rows)} entries.")
    w(f"    inline constexpr std::array<tDtcDbEntry, {len(rows)}> c_dtcDb{{{{")

    for cat, code, desc in rows:
        cat_expr = _CATEGORY_MAP[cat]
        code_hex = f"0x{code:04X}"
        desc_lit = _cpp_string(desc)
        w(f"        {{ {cat_expr}, {code_hex}, {desc_lit} }},")

    w("    }};")
    w("")
    w("}  // namespace subiediag::obd2")
    w("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def _cli(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description="Generate Obd2DtcDb.h from a DTC CSV.")
    p.add_argument("csv", help="path to DTC CSV")
    p.add_argument("--out", required=True, help="output .h path")
    args = p.parse_args(argv)

    csv_path = Path(args.csv)
    out_path = Path(args.out)

    if not csv_path.is_file():
        print(f"error: CSV not found: {csv_path}", file=sys.stderr)
        return 2

    out_path.parent.mkdir(parents=True, exist_ok=True)
    rows = _parse_csv(csv_path)
    _emit(rows, csv_path, out_path)
    print(f"wrote {len(rows)} entries to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli(sys.argv[1:]))
